# Black + usort
[[linter]]
code = 'UFMT'
include_patterns = [
    '**/*.py',
]
command = [
    'python3',
    'tests/lint/ufmt_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
exclude_patterns = [
    '.github/*',
    'build/*',
    'cmake/*',
    'conda/*',
    'docker/*',
    'third_party/*',
]
init_command = [
    'python3',
    'tests/lint/pip_init.py',
    '--dry-run={{DRYRUN}}',
    '--no-black-binary',
    'black==22.3.0',
    'ufmt==1.3.3',
    'usort==1.0.2',
]
is_formatter = true

[[linter]]
code = 'CLANGFORMAT'
include_patterns = [
    '**/*.h',
    '**/*.cc',
    '**/*.cuh',
    '**/*.cu',
]
exclude_patterns = [
]
init_command = [
    'python3',
    'tests/lint/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'clang-format==14.0.6',
]
command = [
    'python3',
    'tests/lint/clangformat_linter.py',
    '--binary=clang-format',
    '--',
    '@{{PATHSFILE}}'
]
is_formatter = true
