name: kg-ci
dependencies:
  - python=3.6.9
  - pip
  - pip:
    - torch
    - torchvision
    - mxnet-cu101
    - pytest
  - nose
  - numpy
  - cython
  - scipy
  - networkx
  - matplotlib
  - nltk
  - requests[security]
  - tqdm