name: mxnet-ci
dependencies:
  - python=3.6.9
  - pip
  - pip:
    - mxnet==1.6.0
    - pytest
    - nose
    - numpy
    - cython
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
