name: mxnet-ci
dependencies:
  - python=3.7.0
  - pip
  - pip:
    - mxnet-cu101==1.7.0
    - pytest
    - nose
    - numpy
    - cython
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
