name: tensorflow-ci
dependencies:
  - python=3.7
  - pip
  - pip:
    - tensorflow==2.3.0
    - pytest
    - nose
    - numpy
    - cython==0.29
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
    - psutil
    - pyyaml
    - pydantic
    - pandas
    - rdflib
    - ogb
