name: tensorflow-ci
dependencies:
  - python=3.6.9
  - pip
  - pip:
    - tensorflow==2.2.0
    - tfdlpack-gpu
    - pytest
    - nose
    - numpy
    - cython
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
